
#macro CRAZY_XSOLLA_EVENT_INIT "init"
#macro CRAZY_XSOLLA_EVENT_OPEN "open"
#macro CRAZY_XSOLLA_EVENT_LOAD "load"
#macro CRAZY_XSOLLA_EVENT_STATUS "status"
#macro CRAZY_XSOLLA_EVENT_STATUS_INVOICE "status-invoice"
#macro CRAZY_XSOLLA_EVENT_STATUS_DELIVERING "status-delivering"
#macro CRAZY_XSOLLA_EVENT_STATUS_DONE "status-done"
#macro CRAZY_XSOLLA_EVENT_CLOSE "close"
#macro CRAZY_XSOLLA_EVENT_ERROR "error"

enum CRAZY_BANNER_POSITION
{
	LEFT_TOP = 0,
	CENTER_TOP = 1,
	RIGHT_TOP = 2,
	
	LEFT_MIDDLE = 10,
	CENTER_MIDDLE = 11,
	RIGHT_MIDDLE = 12,
	
	LEFT_BOTTOM = 20,
	CENTER_BOTTOM = 21,
	RIGHT_BOTTOM = 22,
}
